### ISSUE TITLE
Issues with the tool / something I do wrong i guess

### ISSUE THREAD

**Issue by dansche** [chrsr/solar-monitor#1]
Would love to build that what you have done, but somehow I have no success, the Overview works, so 1_solaredgetime is ok, no error and I get an output to it while testing on AWS

2_solaredgedetails I get errors, output is:
Response:
{
  "errorType": "TypeError",
  "errorMessage": "Cannot read property 'Payload' of undefined",
  "trace": [
    "TypeError: Cannot read property 'Payload' of undefined",
    "    at Runtime.exports.handler (/var/task/index.js:6:42)",
    "    at Runtime.handleOnce (/var/runtime/Runtime.js:66:25)"
  ]
}

3_iftttwebhook does not work as well with me, following errors:
Response:
{
  "errorType": "TypeError",
  "errorMessage": "Cannot read property 'Payload' of undefined",
  "trace": [
    "TypeError: Cannot read property 'Payload' of undefined",
    "    at Runtime.exports.handler (/var/task/index.js:10:30)",
    "    at Runtime.handleOnce (/var/runtime/Runtime.js:66:25)"
  ]
}

Do you have a hint for me what I am doing wrong? I guess 3 is not working because of 2.

Would appreciate your help... very much beginner here...

API Key from SolarEdge and Site Id I changed, and this seems to work because 1_solaredgetime works and brings back the following result:
Response:
{
  "overview": {
    "lastUpdateTime": "2020-08-11 11:48:23",
    "lifeTimeData": {
      "energy": 12473005,
      "revenue": 623.5971
    },
    "lastYearData": {
      "energy": 11816433
    },
    "lastMonthData": {
      "energy": 655243
    },
    "lastDayData": {
      "energy": 22985
    },
    "currentPower": {
      "power": 3969
    },
    "measuredBy": "INVERTER"
  }
}

**Comment by chrsr** [comment]
Hi @dansche - sounds like the input for the second step (details) isn't being passed through correctly - the script is looking for `event.Input.Payload` here: https://github.com/chrsr/solar-monitor/blob/master/2_solaredgedetails.js#L7 - so that error suggests that `event.Input` is null (empty).

Can you double check the step function definition (`json` file)? It should match this: https://github.com/chrsr/solar-monitor/blob/master/statemachine.json#L9

Don't forget to replace each `FunctionName` value with the correct ARN (Amazon Resource Name) for each Lambda function. Replace these values: https://github.com/chrsr/solar-monitor/blob/master/statemachine.json#L9 (i.e. `1_LAMBDA_ARN` is replaced by the `2_solaredgedetails.js` ARN).

Individually the scripts won't work if just testing from AWS Lambda (except for the first one) - they need to be in sequence because they depend on the values passed through between each step in the State Machine.

**Comment by dansche** [comment]
I think it's the function name than i didn't change, looks like this right now:
{
  "Comment": "SolarEdgeMonitor",
  "StartAt": "1_solaredgetime",
  "States": {
    "1_solaredgetime": {
      "Type": "Task",
      "Resource": "arn:aws:lambda:us-east-2:222903815286:function:1_solaredgetime",
      "Parameters": {
        "FunctionName": "1_LAMBDA_ARN"
      },
      "Next": "2_solaredgedetails",
      "TimeoutSeconds": 30
    },
    "2_solaredgedetails": {
      "Type": "Task",
      "Resource": "arn:aws:lambda:us-east-2:222903815286:function:2_solaredgedetails",
      "Parameters": {
        "FunctionName": "2_LAMBDA_ARN",
        "Payload": {
          "Input.$": "$"
        }
      },
      "Next": "3_iftttwebhook",
      "TimeoutSeconds": 30
    },
    "3_iftttwebhook": {
      "Type": "Task",
      "Resource": "arn:aws:lambda:us-east-2:222903815286:function:3_iftttwebhook",
      "Parameters": {
        "FunctionName": "3_LAMBDA_ARN",
        "Payload": {
          "Input.$": "$"
        }
      },
      "TimeoutSeconds": 30,
      "End": true
    }
  }
}

**Comment by dansche** [comment]
Everything is green right now, Script seems to run, have to wait now for the Smart Bulb to test if it works, great thing, will come back if I'm allowed if I have further issues, hope this is ok.

Thanks

Changed now to that:
{
  "Comment": "SolarEdgeMonitor",
  "StartAt": "1_solaredgetime",
  "States": {
    "1_solaredgetime": {
      "Type": "Task",
      "Resource": "arn:aws:states:::lambda:invoke",
      "Parameters": {
        "FunctionName": "arn:aws:lambda:us-east-2:222903815286:function:1_solaredgetime"
      },
      "Next": "2_solaredgedetails",
      "TimeoutSeconds": 30
    },
    "2_solaredgedetails": {
      "Type": "Task",
      "Resource": "arn:aws:states:::lambda:invoke",
      "Parameters": {
        "FunctionName": "arn:aws:lambda:us-east-2:222903815286:function:2_solaredgedetails",
        "Payload": {
          "Input.$": "$"
        }
      },
      "Next": "3_iftttwebhook",
      "TimeoutSeconds": 30
    },
    "3_iftttwebhook": {
      "Type": "Task",
      "Resource": "arn:aws:states:::lambda:invoke",
      "Parameters": {
        "FunctionName": "arn:aws:lambda:us-east-2:222903815286:function:3_iftttwebhook",
        "Payload": {
          "Input.$": "$"
        }
      },
      "TimeoutSeconds": 30,
      "End": true
    }
  }
}

**Comment by chrsr** [comment]
Great. How did it go @dansche ? Did the light turn on / off?

For debugging you can look at the output in the Step Function results.

Finally, the CRON timing that I used runs the script every 5 mins, which is probably more often than required. Last month I received a bill for this for around $1 USD (shocking!) - so if you want it to run totally free, you can reduce the CRON frequency :)

**Comment by dansche** [comment]
Well finally the Bulp arrived, something I still have wrong, hope you can give me a hint, just ask what you need to see, the only thing it does, is to turn the Bulp_off.... even yes we do produce as I can see out of the outputs:

See here:
Step One result:
{
  "name": "1_solaredgetime",
  "output": {
    "ExecutedVersion": "$LATEST",
    "Payload": {
      "overview": {
        "lastUpdateTime": "2020-08-14 11:10:17",
        "lifeTimeData": {
          "energy": 12650135,
          "revenue": 632.45355
        },
        "lastYearData": {
          "energy": 11993563
        },
        "lastMonthData": {
          "energy": 832373
        },
        "lastDayData": {
          "energy": 8198
        },
        "currentPower": {
          "power": 9580
        },
        "measuredBy": "INVERTER"
      }
    },
    "SdkHttpMetadata": {
      "AllHttpHeaders": {
        "X-Amz-Executed-Version": [
          "$LATEST"
        ],
        "x-amzn-Remapped-Content-Length": [
          "0"
        ],
        "Connection": [
          "keep-alive"
        ],
        "x-amzn-RequestId": [
          "bd0fffc0-e297-4b01-9328-b6e7809ce2cd"
        ],
        "Content-Length": [
          "261"
        ],
        "Date": [
          "Fri, 14 Aug 2020 09:14:37 GMT"
        ],
        "X-Amzn-Trace-Id": [
          "root=1-5f3655fc-0d68b7088b5c125866f64d48;sampled=0"
        ],
        "Content-Type": [
          "application/json"
        ]
      },
      "HttpHeaders": {
        "Connection": "keep-alive",
        "Content-Length": "261",
        "Content-Type": "application/json",
        "Date": "Fri, 14 Aug 2020 09:14:37 GMT",
        "X-Amz-Executed-Version": "$LATEST",
        "x-amzn-Remapped-Content-Length": "0",
        "x-amzn-RequestId": "bd0fffc0-e297-4b01-9328-b6e7809ce2cd",
        "X-Amzn-Trace-Id": "root=1-5f3655fc-0d68b7088b5c125866f64d48;sampled=0"
      },
      "HttpStatusCode": 200
    },
    "SdkResponseMetadata": {
      "RequestId": "bd0fffc0-e297-4b01-9328-b6e7809ce2cd"
    },
    "StatusCode": 200
  },
  "outputDetails": null
}




Step 2 result:
{
  "name": "2_solaredgedetails",
  "output": {
    "ExecutedVersion": "$LATEST",
    "Payload": {
      "powerDetails": {
        "timeUnit": "QUARTER_OF_AN_HOUR",
        "unit": "W",
        "meters": [
          {
            "type": "Production",
            "values": [
              {
                "date": "2020-08-14 11:00:00",
                "value": 7019
              }
            ]
          }
        ]
      }
    },
    "SdkHttpMetadata": {
      "AllHttpHeaders": {
        "X-Amz-Executed-Version": [
          "$LATEST"
        ],
        "x-amzn-Remapped-Content-Length": [
          "0"
        ],
        "Connection": [
          "keep-alive"
        ],
        "x-amzn-RequestId": [
          "4cf337fd-e3fe-4b9e-abf6-dfcaf3e0ecb6"
        ],
        "Content-Length": [
          "149"
        ],
        "Date": [
          "Fri, 14 Aug 2020 09:14:38 GMT"
        ],
        "X-Amzn-Trace-Id": [
          "root=1-5f3655fd-4c9e2778b927f2b07aee2350;sampled=0"
        ],
        "Content-Type": [
          "application/json"
        ]
      },
      "HttpHeaders": {
        "Connection": "keep-alive",
        "Content-Length": "149",
        "Content-Type": "application/json",
        "Date": "Fri, 14 Aug 2020 09:14:38 GMT",
        "X-Amz-Executed-Version": "$LATEST",
        "x-amzn-Remapped-Content-Length": "0",
        "x-amzn-RequestId": "4cf337fd-e3fe-4b9e-abf6-dfcaf3e0ecb6",
        "X-Amzn-Trace-Id": "root=1-5f3655fd-4c9e2778b927f2b07aee2350;sampled=0"
      },
      "HttpStatusCode": 200
    },
    "SdkResponseMetadata": {
      "RequestId": "4cf337fd-e3fe-4b9e-abf6-dfcaf3e0ecb6"
    },
    "StatusCode": 200
  },
  "outputDetails": null
}

Step 3 result:
{
  "name": "3_iftttwebhook",
  "output": {
    "ExecutedVersion": "$LATEST",
    "Payload": "Congratulations! You've fired the SolarEdge_BulpOff event",
    "SdkHttpMetadata": {
      "AllHttpHeaders": {
        "X-Amz-Executed-Version": [
          "$LATEST"
        ],
        "x-amzn-Remapped-Content-Length": [
          "0"
        ],
        "Connection": [
          "keep-alive"
        ],
        "x-amzn-RequestId": [
          "b865ba8b-aecf-42c6-90f6-53f810a608d9"
        ],
        "Content-Length": [
          "59"
        ],
        "Date": [
          "Fri, 14 Aug 2020 09:14:38 GMT"
        ],
        "X-Amzn-Trace-Id": [
          "root=1-5f3655fe-b3cb9700781bd2f0bee30090;sampled=0"
        ],
        "Content-Type": [
          "application/json"
        ]
      },
      "HttpHeaders": {
        "Connection": "keep-alive",
        "Content-Length": "59",
        "Content-Type": "application/json",
        "Date": "Fri, 14 Aug 2020 09:14:38 GMT",
        "X-Amz-Executed-Version": "$LATEST",
        "x-amzn-Remapped-Content-Length": "0",
        "x-amzn-RequestId": "b865ba8b-aecf-42c6-90f6-53f810a608d9",
        "X-Amzn-Trace-Id": "root=1-5f3655fe-b3cb9700781bd2f0bee30090;sampled=0"
      },
      "HttpStatusCode": 200
    },
    "SdkResponseMetadata": {
      "RequestId": "b865ba8b-aecf-42c6-90f6-53f810a608d9"
    },
    "StatusCode": 200
  },
  "outputDetails": null
}



As you can see, I did produce 7019 Watts, the Webhook is running as well ok on IFTT I have enabled messaging when an event gets triggered for the moment, so I receive an Information, that the Applet Run: SolarEdge_BulpOff.... but in this case it should run the SolarEdge_BulpOn applet.

Don't use the Cron Job for the moment, have it to run every 15 minutes for the moment.

What is not given to step 3 that it triggers the wrong thing.

Thanks for your help.

Daniel

**Comment by dansche** [comment]
So I tested further on and I found the error, as I don't use consumption on SolarEdge as I use another SmartDevice to measure consumption, there the error came from, had to take out the consumption part. 

Looks than like that in the 3_iftttwebhook:
const https = require('https')

exports.handler = async (event) => {

  const API_KEY = "m4C1waso"
  const EVENTS = {
    on: "SolarEdge_BulpOn",
    off: "SolarEdge_BulpOff"
  }
  const meters = event.Input.Payload.powerDetails.meters

  function areWeProducing(meters) {
    let production
    meters.forEach(meter => {
      if (meter.type === "Production") production = meter.values[0].value
    })
    return production
  }

  const iftttevent = areWeProducing(meters) ? EVENTS.on : EVENTS.off

  let options = {
    host: `maker.ifttt.com`,
    port: 443,
    path: `/trigger/${iftttevent}/with/key/${API_KEY}`,
    method: 'POST',
    headers: {
      'Content-Type': 'application/json'
    }
  }

  const response = await new Promise((resolve, reject) => {
    const post_req = https.request(options, (res) => {
      let iftttRes = ''
      res.on('data', (chunk) => {
        iftttRes += chunk
      })
      res.on('end', () => { 
        resolve(iftttRes)
      })
      post_req.on('error', (error) => {
        reject({
          statusCode: 500,
          body: error
        })
      })
    })
    post_req.write("");
    post_req.end();
  })
  return response
}




So now my next and last request ;-)

I see, the value between the brackets is (0), how can I make, that the light turns on when I produce 1000 or 2000 or 3000 Watts,

**Comment by dansche** [comment]
function areWeProducing(meters) {
    let production
    meters.forEach(meter => {
      if (meter.type === "Production") production = meter.values[0].value >2000
    })
    return production


Did that, that does the trick, now it seems up and running, Bulp turns on when production is above 2000W

Sorry problems solved by itself respectively, with myself and google.

**Comment by chrsr** [comment]
Great work.

The `areWeProducing` function is supposed to work out if your system is producing more than you are consuming. The change you have made will just tell if it's above 2000W

Are you able to share a sample output of `2_solaredgedetails.js` - strange that the consumption portion is missing.

Final note, just be careful sharing API keys publicly - I can see your IFTTT key in the post above - no dramas, just that anyone can now turn off your bulb :)

**Comment by chrsr** [comment]
Would still love to hear how you got on @dansche
